FROM busybox
# Downloading gcloud package
RUN curl https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz > /tmp/google-cloud-sdk.tar.gz
#COPY /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/gcloud /gcloud
#RUN curl -sSL https://sdk.cloud.google.com > /tmp/gcl && bash /tmp/gcl --install-dir=~/gcloud --disable-prompts
# COPY test.txt test.txt
# RUN curl --version
# RUN echo "hostname"