domain                    = "dev.gcp-foundation.com"
billing_account           = "01736F-3BD7F5-42CA41"
region                    = "europe-west2"
terraform_service_account = "org-terraform@prj-b-seed-2400.iam.gserviceaccount.com"
tenant_name               = "pathfinder"
environment               = "dev"
